Q:

rosbridge and rosjs/actionlib Fails

I am trying to run the sample HTML page given in Bosch's remote_lab/rosjs_tutorials package to create an actionlib client in Javascript (tutorial_actionlib.html). The client can connect to rosbridge, connect to the action server, but fails when sending the action. Here is the output given from the client:
Connecting to rosbridge.
Connection to rosbridge established.
Waiting for fibonacci action server to come online.
Sending goal to action server.
Waiting for results from action server.
Didn't receive results from action server.

It looks as if something is going wrong on the rosbridge side of things. Here is the output:
subscribing to: /fibonacci/status
subscribing to: /fibonacci/result
subscribing to: /fibonacci/feedback
Problem Problem Problem Problem Problem Problem Problem Problem Problem Problem 
Traceback (most recent call last):
  File "/home/rail/ROS/brown_remotelab/rosbridge/bin/rosbridge.py", line 57, in handleFrameHelper
    session.publishers[receiver].publish(ros.specify(typ,msg))
  File "/home/rail/ROS/brown_remotelab/rosbridge/bin/ROSProxy/ROSProxy.py", line 152, in specify
    value = self.specify(typ,obj[field])
  File "/home/rail/ROS/brown_remotelab/rosbridge/bin/ROSProxy/ROSProxy.py", line 152, in specify
    value = self.specify(typ,obj[field])
  File "/home/rail/ROS/brown_remotelab/rosbridge/bin/ROSProxy/ROSProxy.py", line 134, in specify
    inst = roslib.rostime.Time()
AttributeError: 'module' object has no attribute 'rostime'
Problem Problem Problem Problem Problem Problem Problem Problem Problem Problem

I am running the current experimental SVN build of rosbridge (needed to work on Fuerte) on Ubuntu 12.04 using ROS Fuerte. I know that there were some problems with rostime and Fuerte a few weeks ago and did not know enough about the inner workings of rosbridge to know if this was related or a different problem. Any thoughts are greatly appreciated!

Originally posted by rtoris288 on ROS Answers with karma: 1173 on 2012-06-26
Post score: 0

Original comments
Comment by BeuBeu on 2012-06-26:
Hi,
You should take a look to this answer.
http://answers.ros.org/question/33825/rosbridge-error-in-rosproxypy-on-fuerte-with/?answer=34112#post-id-34112
Benoit
Comment by rtoris288 on 2012-06-27:
Thanks for the response! Unfortunately, I am actually using the version of rosbridge with the fix stated in that post (I actually linked to the same post in my original question :) ). Still investigating!
Comment by Sarah Osentoski on 2012-06-28:
I just tried to duplicate this problem and was unable to.  I am using revision 2891.  Which version are you running?
Comment by rtoris288 on 2012-06-28:
2891 as well... turns out there was a local modification that I was unaware of. Sorry for the waste of time :)

A:

Problem resolved... turns out there was a local modification that I was unaware of. Sorry for the waste of time :)

Originally posted by rtoris288 with karma: 1173 on 2012-06-28
This answer was ACCEPTED on the original site
Post score: 0

