Q:

Cannot find qt_gui in groovy (Ubuntu 64-bit VM)

Hi all,
I'm trying to do the tutorials, but I'm running into lots of trouble with using anything rqt related.  For example, in the tutorial on the rqt_console (http://www.ros.org/wiki/ROS/Tutorials/UsingRqtconsoleRoslaunch), I try rosrun rqt_console rqt_console and get the output below.  I noticed I"m having a permission denied error, but I'm not sure how to get around that.  Does anybody have any suggestions?
Traceback (most recent call last):
  File "/opt/ros/groovy/bin/roswtf", line 35, in <module>
    roswtf.roswtf_main()
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roswtf/__init__.py", line 87, in roswtf_main
    _roswtf_main()
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roswtf/__init__.py", line 136, in _roswtf_main
    static_plugins, online_plugins = roswtf.plugins.load_plugins()
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roswtf/plugins.py", line 54, in load_plugins
    to_check = rospack.get_depends_on('roswtf', implicit=False)
  File "/usr/lib/pymodules/python2.7/rospkg/rospack.py", line 229, in get_depends_on
    m = self.get_manifest(r)
  File "/usr/lib/pymodules/python2.7/rospkg/rospack.py", line 133, in get_manifest
    return self._load_manifest(name)
  File "/usr/lib/pymodules/python2.7/rospkg/rospack.py", line 172, in _load_manifest
    retval = self._manifests[name] = parse_manifest_file(self.get_path(name), self._manifest_name)
  File "/usr/lib/pymodules/python2.7/rospkg/manifest.py", line 376, in parse_manifest_file
    _static_rosdep_view = init_rospack_interface()
  File "/usr/lib/pymodules/python2.7/rosdep2/rospack.py", line 55, in init_rospack_interface
    lookup = _get_default_RosdepLookup(Options())
  File "/usr/lib/pymodules/python2.7/rosdep2/main.py", line 107, in _get_default_RosdepLookup
    verbose=options.verbose)
  File "/usr/lib/pymodules/python2.7/rosdep2/sources_list.py", line 522, in create_default
    sources = load_cached_sources_list(sources_cache_dir=sources_cache_dir, verbose=verbose)
  File "/usr/lib/pymodules/python2.7/rosdep2/sources_list.py", line 429, in load_cached_sources_list
    with open(cache_index, 'r') as f:
IOError: [Errno 13] Permission denied: '/home/my_username/.ros/rosdep/sources.cache/index'
my_username@ubuntu:~$ sudo roswtf
sudo: roswtf: command not found
my_username@ubuntu:~$ rosrun rqt_console rqt_console 
WARNING(s) in /opt/ros/groovy/share/camera_info_manager/package.xml:
- The test dependency on "rostest" is redundant with: build_depend, run_depend
WARNING(s) in /opt/ros/groovy/share/diagnostic_analysis/package.xml:
- The test dependency on "rosbag" is redundant with: build_depend, run_depend
- The test dependency on "rostest" is redundant with: build_depend
- The test dependency on "diagnostic_msgs" is redundant with: build_depend, run_depend
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/rosdep2/rospack.py", line 55, in init_rospack_interface
    lookup = _get_default_RosdepLookup(Options())
  File "/usr/lib/pymodules/python2.7/rosdep2/main.py", line 107, in _get_default_RosdepLookup
    verbose=options.verbose)
  File "/usr/lib/pymodules/python2.7/rosdep2/sources_list.py", line 522, in create_default
    sources = load_cached_sources_list(sources_cache_dir=sources_cache_dir, verbose=verbose)
  File "/usr/lib/pymodules/python2.7/rosdep2/sources_list.py", line 429, in load_cached_sources_list
    with open(cache_index, 'r') as f:
IOError: [Errno 13] Permission denied: '/home/my_username/.ros/rosdep/sources.cache/index'
[rospack] Error: could not call python function 'rosdep2.rospack.init_rospack_interface'
[librospack]: error while executing command
terminate called after throwing an instance of 'pluginlib::LibraryLoadException'
  what():  rospack co

Originally posted by aespielberg on ROS Answers with karma: 113 on 2013-03-03
Post score: 0

A:

This sounds like a rosdep usage issue similar to this thread.

Originally posted by 130s with karma: 10937 on 2013-03-03
This answer was ACCEPTED on the original site
Post score: 0

Original comments
Comment by aespielberg on 2013-03-03:
My hero!  Thanks!

