Q:

rosbridge error in ROSProxy.py on Fuerte with roslib.rostime

rosbridge.py fails on Fuerte after trying to import roslib.rostime.  It seems like this problem can be fixed by replacing all 3 instances of "roslib.rostime" in the code with "rospy.rostime" (although I haven't thoroughly tested this yet).  I don't have any experience with the patching process, but I wanted to get this fix out there, and I would appreciate it if someone could update the code.  Here was the original error:
Traceback (most recent call last):
File "/opt/ros/fuerte/stacks/brown_remotelab/rosbridge/bin/rosbridge.py", line 2, in 
from ROSProxy import ROSProxy
File "/opt/ros/fuerte/stacks/brown_remotelab/rosbridge/bin/ROSProxy/init.py", line 1, in 
from ROSProxy import ROSProxy
File "/opt/ros/fuerte/stacks/brown_remotelab/rosbridge/bin/ROSProxy/ROSProxy.py", line 6, in 
import roslib.rostime
ImportError: No module named rostime

Originally posted by Dave on ROS Answers with karma: 66 on 2012-05-12
Post score: 1

A:

Sorry it took so long to get this fixed, but the latest experimental version of rosbridge passes our regression test and should be fully Fuerte compatible.
As soon as we've done enough testing to make sure there are no hidden gotcha's we'll release a deb (apt-get) version.
In the meantime you can get this version via the usual SVN mechanism:
svn co http://brown-ros-pkg.googlecode.com/svn/trunk/experimental/rosbridge rosbridge

As I said, we're definitely looking to get this version thoroughly tested. Please let us know if you run into any further issues.

Originally posted by tjay with karma: 461 on 2012-05-15
This answer was ACCEPTED on the original site
Post score: 2

Original comments
Comment by Dave on 2012-05-19:
Thanks, I appreciate the fix!  Rosbridge is a great tool!

