Q:

Turtlebot_bringup[WARN]Create : robot not connected yet, sci not available

Hi, every body.
When I use the command line "roslaunch turtlebot_bringup minimal.launch", this "[warn]Create: robot not connected yet, sci not available" always occurs. I use the Hydro edition in Ubuntu 12.04. And the turtlebot was bulid by myself with a Lenovo laptop and iRobot Create.
Here is the detail:
> turtlebot@turtlebot:~/turtlebot/src/irobot/irobot_create_2_1/src/irobot_create_2_1$
> roslaunch turtlebot_bringup
> minimal.launch  ... logging to
> /home/turtlebot/.ros/log/45c9215e-d42b-11e3-9c80-001e6557542c/roslaunch-turtlebot-14349.log
> Checking log directory for disk usage.
> This may take awhile. Press Ctrl-C to
> interrupt Done checking log file disk
> usage. Usage is <1GB.
> 
> started roslaunch server
> http://192.168.1.104:48516/
> 
> SUMMARY
> ========
> 
> PARAMETERS  *
> /cmd_vel_mux/yaml_cfg_file  *
> /diagnostic_aggregator/analyzers/digital_io/path
> * /diagnostic_aggregator/analyzers/digital_io/startswith
> * /diagnostic_aggregator/analyzers/digital_io/timeout
> * /diagnostic_aggregator/analyzers/digital_io/type
> * /diagnostic_aggregator/analyzers/mode/path
> * /diagnostic_aggregator/analyzers/mode/startswith
> * /diagnostic_aggregator/analyzers/mode/timeout
> * /diagnostic_aggregator/analyzers/mode/type
> * /diagnostic_aggregator/analyzers/nodes/contains
> * /diagnostic_aggregator/analyzers/nodes/path
> * /diagnostic_aggregator/analyzers/nodes/timeout
> * /diagnostic_aggregator/analyzers/nodes/type
> * /diagnostic_aggregator/analyzers/power/path
> * /diagnostic_aggregator/analyzers/power/startswith  * /diagnostic_aggregator/analyzers/power/timeout
> * /diagnostic_aggregator/analyzers/power/type
> * /diagnostic_aggregator/analyzers/sensors/path
> * /diagnostic_aggregator/analyzers/sensors/startswith
> * /diagnostic_aggregator/analyzers/sensors/timeout
> * /diagnostic_aggregator/analyzers/sensors/type
> * /diagnostic_aggregator/base_path  * /diagnostic_aggregator/pub_rate  *
> /robot/name  * /robot/type  *
> /robot_description  *
> /robot_pose_ekf/freq  *
> /robot_pose_ekf/imu_used  *
> /robot_pose_ekf/odom_used  *
> /robot_pose_ekf/output_frame  *
> /robot_pose_ekf/publish_tf  *
> /robot_pose_ekf/sensor_timeout  *
> /robot_pose_ekf/vo_used  *
> /robot_state_publisher/publish_frequency
> * /rosdistro  * /rosversion  * /turtlebot_laptop_battery/acpi_path  *
> /turtlebot_node/bonus  *
> /turtlebot_node/port  *
> /turtlebot_node/update_rate  *
> /use_sim_time
> 
> NODES   /
>     cmd_vel_mux (nodelet/nodelet)
>     diagnostic_aggregator (diagnostic_aggregator/aggregator_node)
>     kinect_breaker_enabler (create_node/kinect_breaker_enabler.py)
>     mobile_base_nodelet_manager (nodelet/nodelet)
>     robot_pose_ekf (robot_pose_ekf/robot_pose_ekf)
>     robot_state_publisher (robot_state_publisher/robot_state_publisher)
>     turtlebot_laptop_battery (linux_hardware/laptop_battery.py)
>     turtlebot_node (create_node/turtlebot_node.py)
> 
> ROS_MASTER_URI=http://192.168.1.104:11311
> 
> core service [/rosout] found
> process[robot_state_publisher-1]:
> started with pid [14370]
> process[diagnostic_aggregator-2]:
> started with pid [14391]
> process[turtlebot_node-3]: started
> with pid [14474]
> process[kinect_breaker_enabler-4]:
> started with pid [14475]
> process[robot_pose_ekf-5]: started
> with pid [14479]
> process[mobile_base_nodelet_manager-6]:
> started with pid [14517]
> process[cmd_vel_mux-7]: started with
> pid [14587] [WARN] [WallTime:
> 1399283836.636816] Create : robot not connected yet, sci not available
> process[turtlebot_laptop_battery-8]:
> started with pid [14669] [WARN]
> [WallTime: 1399283839.642510] Create :
> robot not connected yet, sci not
> available [kinect_breaker_enabler-4]
> process has finished cleanly
> 
> log file:
> /home/turtlebot/.ros/log/45c9215e-d42b-11e3-9c80-001e6557542c/kinect_breaker_enabler-4*.log

I have tried several solutions on the web, but none works.
Some of them are:

Change the permission of /dev/ttyUSB0 using  "chmod 777"

Change the type of TURTLEBOT_BASE in file minimal.launch

Install the driver on the page http://wiki.ros.org/irobot_create_2_1
But this conflicts with the driver in the turtlebot package.

Change the code in turtlebot_node.py:
def set_operation_mode(self,req):
if not self.robot.sci:
raise Exception("Robot not connected, SCI not available")
It is definitely related with self.robot.sci, but I still have no idea of what causes the warningã€‚

Any ideas? Thanks.

Originally posted by Jack Fu on ROS Answers with karma: 11 on 2014-05-05
Post score: 0

A:

Usually that means that the Create is not turned on or the serial cable is not plugged into the robot fully.
There was also an issue if the battery is not charged: http://answers.ros.org/question/62893/turtlebot-bringup-error-robot-not-connected/

Originally posted by tfoote with karma: 58457 on 2014-05-05
This answer was ACCEPTED on the original site
Post score: 0

Original comments
Comment by Jack Fu on 2014-05-05:
In fact, I checked this page before, but it seemed useless.
I'm sure the Create is turned on and the serial cable is plugged into the robot fully, because I can even control it using the keyborad.
The problem is that the warning still occurs.
Comment by tfoote on 2014-05-05:
If you're driving something around with the keyboard it suggests that you are already running the create driver. Thus you shouldn't be launching another copy. Or does it work with this warning appearing?
Comment by Jack Fu on 2014-05-07:
Yes, it works with this warning. I just wonder why the warning occurs. Or maybe I should ignore it.
Thank you so much. :)

