Q:

bloom-release: Failed to open pull request

When I run bloom-release command, to release a package for the first time, everything goes well, until the automatic pull request to rosdistro, where i get: Failed to open pull request: KeyError - 'release'.
This is what I get at the end of the file ~/.bloom_logs/bloom-release_current-date.log:

[debug] /tmp/tmpIUPSBY:$ git ls-tree master:tracks.yaml
[debug] /tmp/tmpIUPSBY:$ git show master:tracks.yaml
[debug] Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.7/bloom/commands/release.py", line 767, in perform_release
    pull_request_url = open_pull_request(track, repository, distro, ssh_pull_request)
  File "/usr/lib/pymodules/python2.7/bloom/commands/release.py", line 418, in open_pull_request
    updated_distribution_file = generate_ros_distro_diff(track, repository, distro)
  File "/usr/lib/pymodules/python2.7/bloom/commands/release.py", line 281, in generate_ros_distro_diff
    repo = distribution_dict['repositories'][repository]['release']
KeyError: 'release'

[error] Failed to open pull request: KeyError - 'release'
[error] SYS.EXIT

Originally posted by czalidis on ROS Answers with karma: 25 on 2014-02-06
Post score: 1

A:

This looks like a failure which should have been fixed with this commit:
https://github.com/ros-infrastructure/bloom/commit/9591792a74d4988fdbcc8986438d673a477af7b0
But is still failing in the case that you have an entry (source or doc) but not a release entry yet in the distribution file.
Can you open a ticket against bloom please?
https://github.com/ros-infrastructure/bloom/issues
EDIT:
I have released bloom-0.4.9 which should address this problem.

Originally posted by William with karma: 17335 on 2014-02-06
This answer was ACCEPTED on the original site
Post score: 1

Original comments
Comment by czalidis on 2014-02-06:
Yes, in my case I have already indexed my packages for doc generation. I opened an issue on github, https://github.com/ros-infrastructure/bloom/issues/229 .

