Q:

roscore doesnt start

I start to run the roscore on ROS hydro, and I get this error :
WARNING: disk usage in log directory [/home/astro/.ros/log] is over 1GB.
It's recommended that you use the 'rosclean' command.

^CTraceback (most recent call last):
  File "/opt/ros/hydro/bin/roscore", line 63, in <module>
    roslaunch.main(['roscore', '--core'] + sys.argv[1:])

  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/__init__.py", line 279, in main
    p.start()

  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/parent.py", line 257, in start
    self._start_infrastructure()

  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/parent.py", line 215, in _start_infrastructure
    self._start_server()

  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/parent.py", line 166, in _start_server
    self.server.start()

  File "/opt/ros/hydro/lib/python2.7/dist-packages/roslaunch/server.py", line 368, in start
    code, msg, val = xmlrpclib.ServerProxy(self.uri).get_pid()

  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)

  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose

  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)

  File "/usr/lib/python2.7/xmlrpclib.py", line 1292, in single_request
    self.send_content(h, request_body)

  File "/usr/lib/python2.7/xmlrpclib.py", line 1439, in send_content
    connection.endheaders(request_body)

  File "/usr/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)

  File "/usr/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)

  File "/usr/lib/python2.7/httplib.py", line 791, in send
    self.connect()

  File "/usr/lib/python2.7/httplib.py", line 772, in connect
    self.timeout, self.source_address)

  File "/usr/lib/python2.7/socket.py", line 562, in create_connection
    sock.connect(sa)

  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)

What is wrong ?
Thank you

Originally posted by Hkev68 on ROS Answers with karma: 1 on 2015-04-30
Post score: 0

Original comments
Comment by Naman on 2015-04-30:
This is a warning which says that your log storage is more than 1 GB.. If you want, you can just run rosclean as suggested.

A:

As warned logs are over 1GB
use rosclean purge to remove logs. check rosclean

Originally posted by bvbdort with karma: 3034 on 2015-04-30
This answer was ACCEPTED on the original site
Post score: 1

