Q:

bloom-release "pull request modifies a repository entry other than the one being released"

Hello!
Trying to release a new version (0.0.5) of ament_virtualenv for dashing, bloom-release ament_virtualenv --rosdistro dashing --track dashing aborted with the following message:
This generated pull request modifies a repository entry other than the one being released.
This likely occurred because the upstream rosdistro changed during this release.
This pull request will abort, please re-run this command with the -p option to try again.

I tried again with -p, but it fails every time.
I deleted everything in /tmp and tried again from scratch but it fails again with the same message.
I released it for crystal and that worked without problems.
I tried again for dashing and get the same error again.
I tried searching for solutions/answers but could not find any.

Does anybody have an idea as to what causes this?
Thanks!

Originally posted by max-krichenbauer on ROS Answers with karma: 17 on 2020-01-10
Post score: 0

Original comments
Comment by gvdhoorn on 2020-01-10:
It would help if you could show us the command line you tried to use.
Comment by max-krichenbauer on 2020-01-10:
Thanks, updated.

A:

Please update your python-rosdistro package. The change was introduced in here: https://github.com/ros-infrastructure/rosdistro/pull/147
Package is available via debians or pip

Originally posted by Karsten with karma: 643 on 2020-01-10
This answer was ACCEPTED on the original site
Post score: 1

Original comments
Comment by gvdhoorn on 2020-01-10:
@Karsten: did you run into this error yourself and is that why you recognise it?
Comment by Karsten on 2020-01-10:
that is correct. I am currently on version 0.8.0 of rosdistro and this seemed to help.
Comment by gvdhoorn on 2020-01-10:
It's rather unfortunate that a seemingly unrelated change results in these kinds of errors. The error message does not give any clue as to what the problem really is.
Was this breakage considered when that PR was merged?
Comment by max-krichenbauer on 2020-01-10:
Thanks a lot! That indeed solved it!

